import {chromium} from 'playwright';
import {mkdir,writeFile,stat} from 'node:fs/promises';
import {resolve} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';

const exec=promisify(execFile);
const base=process.env.REMASTER_QA_URL||'http://localhost:8770';
const out=resolve('delivery/remaster');
await mkdir(resolve(out,'raw'),{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1,
  recordVideo:{dir:resolve(out,'raw'),size:{width:1920,height:1080}}});
const page=await context.newPage(),video=page.video(),errors=[],timecoded=[];
page.on('pageerror',e=>errors.push(e.message));
const start=performance.now();
const mark=label=>timecoded.push({seconds:Number(((performance.now()-start)/1000).toFixed(2)),label});
const at=async seconds=>{const remaining=seconds*1000-(performance.now()-start);if(remaining>0)await page.waitForTimeout(remaining);};
const waitDay=day=>page.waitForFunction(day=>JSON.parse(window.render_game_to_text()).snapshot.day>=day,day,{timeout:140000});
const pause=()=>page.getByRole('button',{name:/^Pause(?: quarter)?$/}).click();
const resume=()=>page.getByRole('button',{name:/^Resume(?: quarter)?$/}).click();
const memory=()=>page.getByRole('button',{name:/Memory X-ray/i}).first().click();
let finalSnapshot;
try{
  await page.goto(`${base}/demo/remaster`);
  await page.locator('#start-btn').waitFor();
  await page.evaluate(()=>document.fonts.ready);
  mark('Actual UI recording. Scripted simulation, synthetic team, deliberate memory fault.');
  await at(4);await page.locator('#start-btn').click();mark('Start the quarter');
  await at(10);await page.getByRole('button',{name:'Introduce a change',exact:true}).click();
  await at(13);await page.locator('[data-preset="sarah-leave"]').click();mark('Inject Sarah week-nine leave through the UI');
  await waitDay(30);await pause();await memory();
  await page.locator('.rm-fact').filter({hasText:'fact-sarah-availability'}).locator('summary').click();
  await page.locator('.rm-memory-ops > details').filter({hasText:'archive'}).first().locator(':scope > summary').click();
  mark('Pause day 30: inspect deliberate archive with source');
  await at(76);await page.keyboard.press('Escape');await resume();
  await waitDay(31);await pause();mark('Pause day 31: Doer / Shadow disagreement');
  await at(84);await memory();await page.locator('.rm-shadow-check').filter({hasText:'divergence'}).first().locator(':scope > summary').click();
  await at(90);await page.keyboard.press('Escape');await resume();
  await waitDay(32);await pause();await memory();
  await page.locator('.rm-memory-ops > details').filter({hasText:'restore'}).first().locator(':scope > summary').click();
  mark('Pause day 32: restore and changed assignment');
  await at(104);await page.keyboard.press('Escape');await resume();
  await waitDay(60);mark('Actual outcome of the fixture rules');
  finalSnapshot=await page.evaluate(()=>JSON.parse(window.render_game_to_text()).snapshot);
  if(finalSnapshot.status!=='completed'||finalSnapshot.metrics.restores!==1||finalSnapshot.receipts.length)throw new Error('Recording did not complete the intended disclosed fixture path.');
  await at(180);
}finally{await context.close();await browser.close();}
if(errors.length)throw new Error(`Browser recording errors: ${errors.join('; ')}`);
const raw=await video.path(),output=resolve(out,'COMPASS_REMaster_Walkthrough_180s_1080p.mp4');
const trimLeadSeconds=0.5;
await exec('ffmpeg',['-hide_banner','-loglevel','error','-y','-ss',String(trimLeadSeconds),'-i',raw,'-an','-vf','fps=30,scale=1920:1080:flags=lanczos,setsar=1,tpad=stop_mode=clone:stop_duration=3','-t','180','-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart',output],{maxBuffer:4e6});
const {stdout}=await exec('ffprobe',['-v','error','-show_entries','format=duration,size:stream=codec_name,codec_type,width,height,r_frame_rate','-of','json',output]);
const probe=JSON.parse(stdout),v=probe.streams.find(s=>s.codec_type==='video');
if(v?.width!==1920||v?.height!==1080||Math.abs(Number(probe.format.duration)-180)>0.2)throw new Error('Unexpected render specification.');
await exec('ffmpeg',['-v','error','-i',output,'-f','null','-'],{maxBuffer:4e6});
const manifest={output,raw,base,createdAt:new Date().toISOString(),scope:'Real interface capture of a scripted simulation. Deliberate fault injection; not a real AI or sponsor run.',audio:'Silent, for live narration using docs/REMASTER_PITCH.md. No licensed media required.',tools:['Playwright Chromium','FFmpeg'],mcpMediaServicesUsed:[],paidGeneration:false,trimLeadSeconds,probe,timecoded:timecoded.map(item=>({...item,seconds:Math.max(0,Number((item.seconds-trimLeadSeconds).toFixed(2)))})),outcome:finalSnapshot.outcome,bytes:(await stat(output)).size};
await writeFile(resolve(out,'video-manifest.json'),JSON.stringify(manifest,null,2));
console.log(JSON.stringify(manifest,null,2));
