import { createVoiceAdapter } from './voice-adapter.js';
const scenes=[...document.querySelectorAll('.scene')], canvas=document.querySelector('#atmosphere'),ctx=canvas.getContext('2d');
const reduced=matchMedia('(prefers-reduced-motion: reduce)'), voice=createVoiceAdapter();
const greeting='Hi, I’m COMPASS. Think out loud. Change your mind. Let’s find your next step.';
const notes=[
 ['Start with a voice, not a prompt','Most useful conversations begin before we know exactly what we mean. COMPASS is a thinking partner concept for that moment. The optional browser greeting says: “'+greeting+'” It is scripted speech, not an AI reply.'],
 ['The human problem','Sometimes “I’m not sure” is the most honest starting point. Our protagonist has a client decision to make. She can speak before she has organized the problem. The image is an illustrative adult character.'],
 ['An interpretation is not a fact','The client wants Friday. That is the one fact we have. Deadline pressure is only an initial interpretation. A useful system should leave room for correction instead of committing too early.'],
 ['The meaningful correction','Actually, Friday is fine. Payment is the problem. Notice how Friday remains fixed while Deadline gives way to Payment. This is the behavior we want to build: change the interpretation without losing what is already known.'],
 ['Keep context visible','The goal remains a clear commitment. Friday still works. Payment is the corrected concern. The next question follows that correction: what terms would help? This visual sequence is prepared, not inferred by a live model.'],
 ['A useful next step','Half upfront and half on delivery. The conversation now produces a specific draft to review. Nothing has been sent. Open the interactive demo to explore prepared conversations and edit a next-step draft.'],
 ['What exists and what remains','Built: this presentation and scripted interactive examples. Next: an open-ended voice prototype. Not measured: latency, correction accuracy, reliability and real-world usefulness. Persistent memory, interruption handling and connected external actions are not implemented.'],
 ['One direction worth testing','We are NAYL and Vincent. COMPASS makes room to think and aims to help us choose the next useful step. It remains a working concept. Not just an answer. A next step.']
];
let current=0,cleanup=null,typeTimer=null,speaking=false,preparing=false,animations=[],raf=0,last=0,time=0,width=0,height=0;
const dots=document.querySelector('.dots');dots.innerHTML=scenes.map((_,i)=>`<button type="button" aria-label="Scene ${i+1}" data-go="${i}"></button>`).join('');
const orb={x:.5,y:.29,r:.135,alpha:1};let target={...orb};
function targetFor(i){const mobile=width<=760;const targets=mobile?[[.5,.30,.18,1],[.84,.22,.068,.45],[.50,.55,.12,.48],[.50,.57,.09,.3],[.50,.42,.13,.6],[.84,.20,.075,.4],[.83,.28,.075,.4],[.50,.30,.16,.9]]:[[.5,.27,.105,1],[.82,.43,.08,.5],[.50,.57,.10,.55],[.51,.53,.09,.5],[.5,.46,.12,.65],[.50,.49,.09,.35],[.5,.34,.08,.3],[.5,.28,.12,1]];const p=targets[i];return {x:p[0],y:p[1],r:p[2],alpha:p[3]};}
function animate(el,keyframes,options={}){if(!el||reduced.matches)return;const a=el.animate(keyframes,{duration:900,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both',...options});animations.push(a);return a;}
function writeDraft(){clearInterval(typeTimer);const el=document.querySelector('#draft-text');const text='Friday works for me.\n\nCan we agree on 50% upfront and 50% on delivery?';if(reduced.matches){el.textContent=text;return;}let n=0;el.textContent='';typeTimer=setInterval(()=>{n+=2;el.textContent=text.slice(0,n);if(n>=text.length){clearInterval(typeTimer);typeTimer=null;}},36);}
function choreography(i){
 const scene=scenes[i];animate(scene.querySelector('.eyebrow'),[{opacity:0,transform:'translateY(16px)'},{opacity:1,transform:'none'}],{delay:100,duration:650});animate(scene.querySelector('h1,h2'),[{opacity:0,transform:'translateY(28px)',filter:'blur(7px)'},{opacity:1,transform:'none',filter:'blur(0px)'}],{delay:180,duration:900});
 if(i===1)animate(scene.querySelector('.human-image'),[{transform:'scale(1.08) translateX(-1%)'},{transform:'scale(1) translateX(0)'}],{duration:7000,easing:'linear'});
 if(i===2)animate(scene.querySelector('.thought-object'),[{opacity:0,transform:'translate(-100px,55px) rotate(-14deg) scale(.84)'},{opacity:1,transform:'translate(0,0) rotate(-5deg) scale(1)'}],{delay:210,duration:1050});
 if(i===3){animate(scene.querySelector('.old-concern'),[{opacity:1,filter:'blur(0px)',transform:'translateX(0)'},{opacity:.32,filter:'blur(.5px)',transform:'translateX(-12px)'}],{delay:300,duration:850});animate(scene.querySelector('.new-concern'),[{opacity:0,transform:'translateX(50px) scale(.85)',filter:'blur(9px)'},{opacity:1,transform:'none',filter:'blur(0px)'}],{delay:520,duration:1050});animate(scene.querySelector('.route-line'),[{opacity:0,clipPath:'inset(0 100% 0 0)'},{opacity:1,clipPath:'inset(0 0 0 0)'}],{delay:360,duration:700});}
 if(i===4)scene.querySelectorAll('.thread-chip').forEach((el,n)=>animate(el,[{opacity:0,transform:`translate(${(1.5-n)*65}px,-50px) scale(.8)`},{opacity:1,transform:'none'}],{delay:180+n*150,duration:950}));
 if(i===5){animate(scene.querySelector('.reply-draft'),[{opacity:0,transform:'translateY(45px) rotate(3deg)'},{opacity:1,transform:'none'}],{delay:150,duration:950});writeDraft();}
 if(i===6)scene.querySelectorAll('.proof-path>div').forEach((el,n)=>animate(el,[{opacity:0,transform:'translateY(30px)'},{opacity:1,transform:'none'}],{delay:180+n*160,duration:850}));
 if(i===7)animate(scene.querySelector('.horizon'),[{transform:'translateY(50px)',opacity:0},{transform:'none',opacity:1}],{duration:1500});
}
function updateNotes(){document.querySelector('#note-title').textContent=notes[current][0];document.querySelector('#note-copy').textContent=notes[current][1];}
function go(next){next=Math.max(0,Math.min(7,Number(next)||0));if(next===current)return;voice.stop();speaking=false;preparing=false;resetHear();clearInterval(typeTimer);clearTimeout(cleanup);animations.forEach(a=>a.cancel());animations=[];
 const prior=scenes[current],direction=next>current?1:-1;scenes.forEach(s=>{s.classList.remove('current','leaving');s.hidden=s!==prior;s.inert=true;s.style.opacity='';});prior.classList.add('leaving');prior.hidden=reduced.matches;current=next;const incoming=scenes[current];incoming.hidden=false;incoming.inert=false;incoming.classList.add('current');target=targetFor(current);
 if(!reduced.matches){animate(prior,[{opacity:1,transform:'translateX(0)',filter:'blur(0px)'},{opacity:0,transform:`translateX(${-direction*65}px) scale(1.025)`,filter:'blur(7px)'}],{duration:800});animate(incoming,[{opacity:0,transform:`translateX(${direction*60}px)`,filter:'blur(4px)'},{opacity:1,transform:'none',filter:'blur(0px)'}],{duration:1000});}else Object.assign(orb,target);
 cleanup=setTimeout(()=>{if(prior!==scenes[current]){prior.hidden=true;prior.classList.remove('leaving');}},reduced.matches?0:1050);choreography(current);updateControls();updateNotes();if(reduced.matches)draw(0);}
function updateControls(){document.querySelector('#previous').disabled=current===0;document.querySelector('#next').disabled=current===7;document.querySelector('#counter').textContent=`${String(current+1).padStart(2,'0')} / 08`;dots.querySelectorAll('button').forEach((b,i)=>{if(i===current)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});}
function resetHear(){document.querySelector('#hear').innerHTML='Hear COMPASS <span>◖</span>';document.querySelector('#voice-status').textContent='Optional browser voice · scripted greeting';}
const hear=document.querySelector('#hear');hear.addEventListener('click',()=>{if(speaking||preparing){voice.stop();resetHear();return;}voice.speak(greeting,{onState(state,detail){speaking=state==='speaking';preparing=state==='preparing';hear.textContent=speaking?'Stop introduction ◼':preparing?'Cancel introduction':'Hear COMPASS ◖';document.querySelector('#voice-status').textContent=detail||({preparing:'Preparing browser voice…',speaking:'Speaking · browser voice · scripted greeting',ended:'Your turn to explore. Use the arrows below.',stopped:'Introduction stopped.'}[state]||'Optional browser voice · scripted greeting');if(reduced.matches)draw(0);}});});
document.querySelector('#previous').addEventListener('click',()=>go(current-1));document.querySelector('#next').addEventListener('click',()=>go(current+1));dots.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go);});document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();go(0);});
function showNotes(value){document.querySelector('#notes').hidden=!value;document.querySelector('#notes-toggle').setAttribute('aria-expanded',String(value));if(value)document.querySelector('#notes-close').focus();}
document.querySelector('#notes-toggle').addEventListener('click',()=>showNotes(document.querySelector('#notes').hidden));document.querySelector('#notes-close').addEventListener('click',()=>{showNotes(false);document.querySelector('#notes-toggle').focus();});
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='Escape'){showNotes(false);voice.stop();return;}if(e.key==='ArrowRight'){e.preventDefault();go(current+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(current-1);}if(e.key==='Home'){e.preventDefault();go(0);}if(e.key==='End'){e.preventDefault();go(7);}if(e.code==='Space'&&!e.target.closest('button,a')){e.preventDefault();go(current+1);}});
function resize(){width=innerWidth;height=innerHeight;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);target=targetFor(current);if(reduced.matches)Object.assign(orb,target);draw(0);}
function draw(dt){if(!ctx)return;const speed=reduced.matches?1:1-Math.exp(-dt*3.6);for(const k of ['x','y','r','alpha'])orb[k]+=(target[k]-orb[k])*speed;
 ctx.clearRect(0,0,width,height);const x=orb.x*width,y=orb.y*height,r=orb.r*Math.min(width,height)*1.55;const pulse=reduced.matches?0:Math.sin(time*.8)*.018;const rr=r*(1+pulse+(speaking&&!reduced.matches?Math.sin(time*6)*.025:0));ctx.save();ctx.globalAlpha=orb.alpha;
 const halo=ctx.createRadialGradient(x,y,rr*.65,x,y,rr*2.6);halo.addColorStop(0,'rgba(120,201,249,.09)');halo.addColorStop(.48,'rgba(90,174,225,.055)');halo.addColorStop(1,'rgba(60,120,200,0)');ctx.fillStyle=halo;ctx.fillRect(x-rr*2.7,y-rr*2.7,rr*5.4,rr*5.4);
 const body=ctx.createRadialGradient(x-rr*.3,y-rr*.35,rr*.02,x,y,rr);body.addColorStop(0,'rgba(126,175,202,.25)');body.addColorStop(.42,'rgba(28,69,94,.6)');body.addColorStop(.8,'rgba(6,24,40,.94)');body.addColorStop(.94,'rgba(27,70,100,.96)');body.addColorStop(1,'rgba(156,213,247,.77)');ctx.beginPath();ctx.arc(x,y,rr,0,Math.PI*2);ctx.fillStyle=body;ctx.fill();
 for(let layer=0;layer<3;layer++){ctx.beginPath();for(let j=0;j<=180;j++){const a=j/180*Math.PI*2;const ripple=reduced.matches?0:Math.sin(a*4+time*.6+layer)*Math.sin(a*7-time*.3)*(.35+layer*.38);const rad=rr+layer*1.2+ripple;const px=x+Math.cos(a)*rad,py=y+Math.sin(a)*rad;j?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.strokeStyle=`rgba(188,232,255,${.55-layer*.15})`;ctx.lineWidth=layer===0?1.2:.6;ctx.shadowColor='#9ad9ff';ctx.shadowBlur=layer===0?12:5;ctx.stroke();}ctx.shadowBlur=0;
 for(let p=0;p<72;p++){const phase=p*2.39996+(reduced.matches?0:time*(.018+(p%4)*.007));const spread=1.08+(p%13)/17;const px=x+Math.cos(phase)*rr*spread,py=y+Math.sin(phase)*rr*spread*.82;const twinkle=reduced.matches?.2:.12+(Math.sin(time*.65+p)+1)*.14;ctx.fillStyle=`rgba(186,229,255,${twinkle})`;ctx.beginPath();ctx.arc(px,py,p%7===0?1.1:.6,0,Math.PI*2);ctx.fill();}
 if(speaking){ctx.beginPath();for(let j=0;j<=160;j++){const t=j/160,px=x+(t-.5)*rr*4;const envelope=Math.exp(-Math.pow((t-.5)*4.5,2));const wave=reduced.matches?Math.sin(t*54)*rr*.07:Math.sin(t*70-time*7)*Math.sin(t*23+time*3)*rr*.18;const py=y+wave*envelope;j?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.strokeStyle='rgba(218,246,255,.85)';ctx.lineWidth=1.2;ctx.shadowColor='#b4eaff';ctx.shadowBlur=10;ctx.stroke();}
 ctx.restore();}
function frame(now){if(document.hidden||reduced.matches){raf=0;return;}const dt=Math.min((now-last)/1000||.016,.05);last=now;time+=dt;draw(dt);raf=requestAnimationFrame(frame);}
function startRender(){if(!raf&&!document.hidden&&!reduced.matches){last=performance.now();raf=requestAnimationFrame(frame);}else if(reduced.matches)draw(0);}
addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;voice.stop();}else startRender();});reduced.addEventListener('change',()=>{cancelAnimationFrame(raf);raf=0;animations.forEach(a=>a.cancel());animations=[];Object.assign(orb,target);if(current===5)writeDraft();startRender();});
scenes.forEach((s,i)=>s.inert=i!==0);resize();updateControls();updateNotes();choreography(0);startRender();
window.COMPASS=Object.freeze({goTo:go,getState:()=>({scene:current+1,speaking,preparing,reducedMotion:reduced.matches,scripted:true,orb:{...orb}})});
